# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spaceport}
  s.version = "3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["djacobs7"]
  s.date = %q{2012-02-14}
  s.default_executable = %q{spaceport}
  s.description = %q{Seriously, this thing is great}
  s.email = %q{daniel@sibblingz.com}
  s.executables = ["spaceport"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README",
    "Rakefile",
    "bin/spaceport",
    "lib/bundle.config",
    "lib/bundle.rb",
    "lib/generate_manifest.rb",
    "lib/lib.rb",
    "lib/server.rb",
    "spaceport.gemspec"
  ]
  s.homepage = %q{http://github.com/sibblingz/spaceport-publisher}
  s.licenses = ["ALL OF THEM"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Bundling tool for spaceport}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<OptionParser>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<OptionParser>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<OptionParser>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

